### ISSUE TITLE
Documentation needed !!

### ISSUE THREAD

**Issue by TobinFrost** [bitlabstudio/django-event-rsvp#1]
Hi!
I am a beginner in RSVP system and in Django.
I would just like to have an example of using your app.
apart from adding event_rsvp to INSTALLED_APPS I do not know where to start.
It would be nice to show an example of use of the app at least for the "profane".

**Comment by Tyrdall** [comment]
@TobinFrost Sorry, this project isn't really maintained anymore and we don't have any resources to teach you Django/Python basics.
